### ISSUE TITLE
The source file for one of the xdelta may not be correct in readme.

### ISSUE THREAD

**Issue by SONIC3D** [TheGent/Gents-N64-xdelta-Patches#1]
The [Yoshi's Story (CHN) [f1].xdelta](https://github.com/TheGent/Gents-N64-xdelta-Patches/blob/main/Bad2Good/iQue/Yoshi's%20Story%20(CHN)%20%5Bf1%5D.xdelta) In [Bad2Good/iQue](https://github.com/TheGent/Gents-N64-xdelta-Patches/tree/main/Bad2Good/iQue) directory is failed to apply to the original dump of this game.

The CRC32 hash of the original ROM dump(in Decrypted, Big Endian format) should be: 9A579A29
Xdelta will report "source file too short: XD3_INVALID_INPUT".

The [Yoshi's Story (CHN) [f2].xdelta](https://github.com/TheGent/Gents-N64-xdelta-Patches/blob/main/Bad2Good/iQue/Yoshi's%20Story%20(CHN)%20%5Bf2%5D.xdelta) in the same directory can be applied to the original dump successfully.

So currently the source file info of the "Yoshi's Story (CHN) [f1].xdelta" is unclear.

**Comment by TheGent** [comment]
Hi @SONIC3D , sorry it took so long to respond, i have just noticed this now.

The issue has been fixed and updated.
I have also updated the ReadMe to reflect the correct information.

Thank you for bringing this to my attention.
