### ISSUE TITLE
Smash Remix

### ISSUE THREAD

**Issue by iceyman** [TheGent/Gents-N64-xdelta-Patches#2]
G'day mate would you like to do an update to Smash Remix to version 1.5.2 please from usa to aust please :D  Thanks

**Comment by TheGent** [comment]
Please make a request on Discord [What NTSC-PAL Patch would you like to see?](https://discord.com/channels/713716215717036034/1204416513403256872) linking to any official release of it and i will see what i can do.

Never mind, Just tried to but results in a Opcode error. I guess the devs have changed something that prevents converting.
